### PR TITLE
Upgrade hapi-auth-jwt for Hapi 17

### PR DESCRIPTION
**Pull request by tanepiper**
This PR is a re-write of the library for Hapi 17 and Node 8.

### CODE REVIEW

**Comment by serranoarevalo** [comment]
Can we get this merged?

**Comment by eduardo-veras** [comment]
Nice job @tanepiper ! I hope this PR get merged soon.

**Comment by MikeLindenau** [comment]
any updates on when this is getting merged?

**Comment by juanprietob** [comment]
I really like this library. Is this going to be merged?

**Comment by antony** [comment]
[hapi-auth-jwt2](https://github.com/dwyl/hapi-auth-jwt2) has been the preferred choice for JWT and Hapi for more than 4 years.

**Pull request closed without merging**
